### PR TITLE
Adding ability to add "Attributes"

### PR DESCRIPTION
**Pull request by hobbeswalsh**
@calston 

Riemann events support Attributes, so I'm adding that capability in Tensor.

I apologize about the gratuitous method signature reformatting; I just thought it was getting a little unwieldy.

I've also added some missing arguments to the docstring. Let me know if this looks okay!

Usage would be from a `Source`:

```python
event = self.createEvent(
    'ok',
    "{} since {} was modified".format(touch_time, filename),
    file_age_in_sec,
    prefix="age",
    attributes={"location": "datacenter1"})
```

### CODE REVIEW

**Comment by hobbeswalsh** [comment]
@calston Sorry for all the bogus commits here; I don't see a way to test this without Travis, unless I were to test it on a VM with Riemann running. Is that right?

**Comment by calston** [comment]
I think we have a fake Riemann server for tests, I'll take a look in the morning - I'm 99% certain there were other tests needing that.

**Comment by hobbeswalsh** [comment]
@calston Thanks. For now, the new test I added passes -- I'm ensuring that the `attribute` keyword arg gets passed on to the actual Protobuf `Event`, which it does.

**Comment by hobbeswalsh** [comment]
@calston Thanks for the merge. Any chance we could get this package published to pypi?

**Comment by calston** [comment]
Yes, I do just want to run it through my testbed and I have some other stuff I want to get into a release.

**Comment by hobbeswalsh** [comment]
@calston great, thanks!

**Comment by calston** [comment]
@hobbeswalsh Release has been published

**Comment by hobbeswalsh** [comment]
@calston Excellent, thanks!

**Pull request merged**
